### ISSUE TITLE
Can't imprt the solution

### ISSUE THREAD

**Issue by quizhyo** [jondoesflow/Teams-Transcript-Summariser-Open-AI#1]
Hi,

Missing dependencies, so I can import solution...can modify it 
![image](https://github.com/user-attachments/assets/3b9d29a6-b6c1-4928-8220-21325f4a7e11)

Could you please share the solution to fix it ?

Many thank !!!

**Comment by jondoesflow** [comment]
Thanks @quizhyo, I have fixed this, version 1_0_0_3 will be in the repo shortly.
